### ISSUE TITLE
Doesn't start :  - ImportError: cannot import name 'VideoDimensions' from 'knowit.properties.video' (/opt/yunohost/bazarr/bazarr/../libs/knowit/properties/video/__init__.py)

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/bazarr_ynh#13]
First i had this error:
```
2022-10-27 19:28:21,310 - root                             (ffff993ef010) :  ERROR (init:209) - BAZARR requires a rar archive extraction utilities (unrar, unar) and it can't be found.
```
even with unrar installed. Installing unar fixed this.

But then, I got that:
```
  - 2022-10-27 19:30:57,481 - apprise                          (ffffbc151010) :  ERROR (__init__:127) - Notification schema (nexmo) mismatch detected - <class 'apprise.plugins.NotifyNexmo.NotifyNexmo'> to <class 'apprise.plugins.NotifyVonage.NotifyVonage'>
  - Traceback (most recent call last):
  -   File "/opt/yunohost/bazarr/bazarr/main.py", line 40, in <module>
  -     from app.signalr_client import sonarr_signalr_client, radarr_signalr_client  # noqa E402
  -   File "/opt/yunohost/bazarr/bazarr/app/signalr_client.py", line 17, in <module>
  -     from sonarr.sync.episodes import sync_episodes, sync_one_episode
  -   File "/opt/yunohost/bazarr/bazarr/sonarr/sync/episodes.py", line 11, in <module>
  -     from subtitles.indexer.series import store_subtitles, series_full_scan_subtitles
  -   File "/opt/yunohost/bazarr/bazarr/subtitles/__init__.py", line 3, in <module>
  -     from . import mass_download  # noqa: W0611
  -   File "/opt/yunohost/bazarr/bazarr/subtitles/mass_download/__init__.py", line 3, in <module>
  -     from .movies import movies_download_subtitles  # noqa: W0611
  -   File "/opt/yunohost/bazarr/bazarr/subtitles/mass_download/movies.py", line 11, in <module>
  -     from subtitles.indexer.movies import store_subtitles_movie
  -   File "/opt/yunohost/bazarr/bazarr/subtitles/indexer/movies.py", line 16, in <module>
  -     from subtitles.tools.embedded_subs_reader import embedded_subs_reader
  -   File "/opt/yunohost/bazarr/bazarr/subtitles/tools/embedded_subs_reader.py", line 8, in <module>
  -     from knowit.api import know
  -   File "/opt/yunohost/bazarr/bazarr/../libs/knowit/__init__.py", line 19, in <module>
  -     from knowit.api import KnowitException, know
  -   File "/opt/yunohost/bazarr/bazarr/../libs/knowit/api.py", line 7, in <module>
  -     from knowit.provider import Provider
  -   File "/opt/yunohost/bazarr/bazarr/../libs/knowit/provider.py", line 8, in <module>
  -     from knowit.properties import Quantity
  -   File "/opt/yunohost/bazarr/bazarr/../libs/knowit/properties/__init__.py", line 18, in <module>
  -     from knowit.properties.video import (
  - ImportError: cannot import name 'VideoDimensions' from 'knowit.properties.video' (/opt/yunohost/bazarr/bazarr/../libs/knowit/properties/video/__init__.py)
  - Bazarr exited.
```

**Comment by Enthouane** [comment]
Same exact issue for me : same error in the logs and bazarr does not start.

**Comment by tituspijean** [comment]
This should be resolved since #35.
